In [15]:
import pandas as pd
import numpy as np
 
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [16]:
url = 'https://raw.githubusercontent.com/gastonstat/CreditScoring/master/CreditScoring.csv'
# !wget $url

In [17]:
data = pd.read_csv("CreditScoring.csv")
df = data.copy()
df.head()

,Status,Seniority,Home,Time,Age,Marital,Records,Job,Expenses,Income,Assets,Debt,Amount,Price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [18]:
df.columns = df.columns.str.lower()
df.columns

Index(['status', 'seniority', 'home', 'time', 'age', 'marital', 'records',
       'job', 'expenses', 'income', 'assets', 'debt', 'amount', 'price'],
      dtype='object')

In [19]:
df.dtypes

status       int64
seniority    int64
home         int64
time         int64
age          int64
marital      int64
records      int64
job          int64
expenses     int64
income       int64
assets       int64
debt         int64
amount       int64
price        int64
dtype: object

categorical: status, home, marital, records, job

In [20]:
categorical = ['status', 'home', 'marital', 'records', 'job']
df[categorical].nunique()

status     3
home       7
marital    6
records    2
job        5
dtype: int64

In [21]:
for col in categorical:
    print(f"{col}: ",df[col].unique())

status:  [1 2 0]
home:  [1 2 5 3 6 4 0]
marital:  [2 3 1 4 5 0]
records:  [1 2]
job:  [3 1 2 0 4]

In [22]:
status_values = {
    1: 'ok',
    2: 'default',
    0: 'unk'
}

df.status = df.status.map(status_values)

home_values = {
    1: 'rent',
    2: 'owner',
    3: 'private',
    4: 'ignore',
    5: 'parents',
    6: 'other',
    0: 'unk'
}

df.home = df.home.map(home_values)

marital_values = {
    1: 'single',
    2: 'married',
    3: 'widow',
    4: 'separated',
    5: 'divorced',
    0: 'unk'
}

df.marital = df.marital.map(marital_values)

records_values = {
    1: 'no',
    2: 'yes',
    0: 'unk'
}

df.records = df.records.map(records_values)

job_values = {
    1: 'fixed',
    2: 'partime',
    3: 'freelance',
    4: 'others',
    0: 'unk'
}

df.job = df.job.map(job_values)

In [23]:
df

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107,0,0,310,910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,default,1,rent,60,39,married,no,fixed,69,92,0,0,900,1020
4451,ok,22,owner,60,46,married,no,fixed,60,75,3000,600,950,1263
4452,default,0,owner,24,37,married,no,partime,60,90,3500,0,500,963
4453,ok,0,rent,48,23,single,no,freelance,49,140,0,0,550,550
4454,ok,5,owner,60,32,married,no,freelance,60,140,4000,1000,1350,1650

In [26]:
df.status.value_counts()

status
ok         3200
default    1254
unk           1
Name: count, dtype: int64

In [30]:
df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0
mean,8.0,46.0,37.0,56.0,763317.0,1060341.0,404382.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,8703625.0,10217569.0,6344253.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1118.0
50%,5.0,48.0,36.0,51.0,120.0,3500.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,166.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,99999999.0,99999999.0,99999999.0,5000.0,11140.0

In [31]:
for c in ['income', 'assets', 'debt']:
    df[c] = df[c].replace(to_replace=99999999, value=np.nan)

In [32]:
df = df[df['status'] != 'unk'].reset_index(drop=True)

In [34]:
df.shape

(4454, 14)

In [35]:
df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4454.0,4454.0,4454.0,4454.0,4420.0,4407.0,4436.0,4454.0,4454.0
mean,8.0,46.0,37.0,56.0,131.0,5404.0,343.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,86.0,11574.0,1246.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1117.0
50%,5.0,48.0,36.0,51.0,120.0,3000.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,165.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,959.0,300000.0,30000.0,5000.0,11140.0

In [36]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=11)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=11)

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = (df_train.status == 'default').astype('int').values
y_val = (df_val.status == 'default').astype('int').values
y_test = (df_test.status == 'default').astype('int').values

del df_train['status']
del df_val['status']
del df_test['status']

In [37]:
df_train

,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,10,owner,36,36,married,no,freelance,75,0.0,10000.0,0.0,1000,1400
1,6,parents,48,32,single,yes,fixed,35,85.0,0.0,0.0,1100,1330
2,1,parents,48,40,married,no,fixed,75,121.0,0.0,0.0,1320,1600
3,1,parents,48,23,single,no,partime,35,72.0,0.0,0.0,1078,1079
4,5,owner,36,46,married,no,freelance,60,100.0,4000.0,0.0,1100,1897
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2667,18,private,36,45,married,no,fixed,45,220.0,20000.0,0.0,800,1600
2668,7,private,60,29,married,no,fixed,60,51.0,3500.0,500.0,1000,1290
2669,1,parents,24,19,single,no,fixed,35,28.0,0.0,0.0,400,600
2670,15,owner,48,43,married,no,freelance,60,100.0,18000.0,0.0,2500,2976
2671,12,owner,48,27,married,yes,fixed,45,110.0,5000.0,1300.0,450,1636

In [39]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import roc_auc_score

In [40]:
train_dicts = df_train.fillna(0).to_dict(orient='records')

dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)

In [41]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [53]:
val_dicts = df_val.fillna(0).to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [59]:
# -- The tree length is too deep which causes overfitting
y_pred = dt.predict_proba(X_train)[:, 1]

roc_auc_score(y_pred, y_train)

1.0

In [57]:
y_pred = dt.predict_proba(X_val)[:, 1]

roc_auc_score(y_pred, y_val)

0.6712715714157025

In [58]:
from sklearn.tree import export_text
print(export_text(dt))

|--- feature_25 <= 0.50
|   |--- feature_27 <= 6.50
|   |   |--- feature_1 <= 862.50
|   |   |   |--- feature_27 <= 0.50
|   |   |   |   |--- class: 1
|   |   |   |--- feature_27 >  0.50
|   |   |   |   |--- feature_12 <= 50.50
|   |   |   |   |   |--- feature_24 <= 1250.00
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_24 >  1250.00
|   |   |   |   |   |   |--- feature_4 <= 75.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_4 >  75.00
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_12 >  50.50
|   |   |   |   |   |--- feature_10 <= 0.50
|   |   |   |   |   |   |--- feature_24 <= 720.00
|   |   |   |   |   |   |   |--- feature_4 <= 52.50
|   |   |   |   |   |   |   |   |--- feature_0 <= 25.50
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_0 >  25.50
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_4 >  52.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_24 >  720.00
|   |   |   |   |   |   |   |--- feature_0 <= 54.00
|   |   |   |   |   |   |   |   |--- feature_2 <= 9500.00
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_2 >  9500.00
|   |   |   |   |   |   |   |   |   |--- feature_27 <= 2.50
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_27 >  2.50
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  54.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_10 >  0.50
|   |   |   |   |   |   |--- feature_2 <= 3500.00
|   |   |   |   |   |   |   |--- feature_1 <= 325.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_1 >  325.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_2 >  3500.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |--- feature_1 >  862.50
|   |   |   |--- feature_2 <= 8250.00
|   |   |   |   |--- feature_13 <= 0.50
|   |   |   |   |   |--- feature_1 <= 2175.00
|   |   |   |   |   |   |--- feature_2 <= 4425.00
|   |   |   |   |   |   |   |--- feature_0 <= 24.50
|   |   |   |   |   |   |   |   |--- feature_24 <= 2036.50
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_24 >  2036.50
|   |   |   |   |   |   |   |   |   |--- feature_19 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_19 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_0 >  24.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_2 >  4425.00
|   |   |   |   |   |   |   |--- feature_10 <= 0.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_10 >  0.50
|   |   |   |   |   |   |   |   |--- feature_1 <= 1300.00
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_1 >  1300.00
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_1 >  2175.00
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_13 >  0.50
|   |   |   |   |   |--- feature_0 <= 31.50
|   |   |   |   |   |   |--- feature_12 <= 133.00
|   |   |   |   |   |   |   |--- feature_12 <= 84.00
|   |   |   |   |   |   |   |   |--- feature_12 <= 67.50
|   |   |   |   |   |   |   |   |   |--- feature_7 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_7 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- feature_2 <= 6000.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- feature_2 >  6000.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_12 >  67.50
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_12 >  84.00
|   |   |   |   |   |   |   |   |--- feature_1 <= 1125.00
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 28.00
|   |   |   |   |   |   |   |   |   |   |--- feature_12 <= 101.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- feature_12 >  101.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_0 >  28.00
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_1 >  1125.00
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_12 >  133.00
|   |   |   |   |   |   |   |--- feature_1 <= 1275.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_1 >  1275.00
|   |   |   |   |   |   |   |   |--- feature_27 <= 4.00
|   |   |   |   |   |   |   |   |   |--- feature_12 <= 179.50
|   |   |   |   |   |   |   |   |   |   |--- feature_12 <= 170.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_12 >  170.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_12 >  179.50
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_27 >  4.00
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_0 >  31.50
|   |   |   |   |   |   |--- feature_8 <= 0.50
|   |   |   |   |   |   |   |--- feature_2 <= 7850.00
|   |   |   |   |   |   |   |   |--- feature_27 <= 2.50
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_27 >  2.50
|   |   |   |   |   |   |   |   |   |--- feature_21 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- feature_1 <= 2150.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |   |   |--- feature_1 >  2150.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_21 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_2 >  7850.00
|   |   |   |   |   |   |   |   |--- feature_27 <= 3.50
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_27 >  3.50
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_8 >  0.50
|   |   |   |   |   |   |   |--- feature_0 <= 35.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  35.50
|   |   |   |   |   |   |   |   |--- feature_24 <= 1249.50
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_24 >  1249.50
|   |   |   |   |   |   |   |   |   |--- feature_1 <= 1525.00
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_1 >  1525.00
|   |   |   |   |   |   |   |   |   |   |--- feature_2 <= 3500.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_2 >  3500.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- feature_2 >  8250.00
|   |   |   |   |--- feature_12 <= 132.50
|   |   |   |   |   |--- feature_1 <= 1100.00
|   |   |   |   |   |   |--- feature_1 <= 887.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_1 >  887.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_1 >  1100.00
|   |   |   |   |   |   |--- feature_0 <= 57.00
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_0 >  57.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_12 >  132.50
|   |   |   |   |   |--- feature_2 <= 42500.00
|   |   |   |   |   |   |--- feature_4 <= 67.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_4 >  67.50
|   |   |   |   |   |   |   |--- feature_12 <= 248.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_12 >  248.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_2 >  42500.00
|   |   |   |   |   |   |--- class: 1
|   |--- feature_27 >  6.50
|   |   |--- feature_12 <= 103.50
|   |   |   |--- feature_2 <= 4500.00
|   |   |   |   |--- feature_28 <= 54.00
|   |   |   |   |   |--- feature_27 <= 12.00
|   |   |   |   |   |   |--- feature_10 <= 0.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_10 >  0.50
|   |   |   |   |   |   |   |--- feature_0 <= 45.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  45.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_27 >  12.00
|   |   |   |   |   |   |--- feature_10 <= 0.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_10 >  0.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_28 >  54.00
|   |   |   |   |   |--- feature_0 <= 48.50
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_0 >  48.50
|   |   |   |   |   |   |--- feature_7 <= 0.50
|   |   |   |   |   |   |   |--- feature_4 <= 47.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_4 >  47.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_7 >  0.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- feature_2 >  4500.00
|   |   |   |   |--- feature_12 <= 50.50
|   |   |   |   |   |--- feature_28 <= 18.00
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_28 >  18.00
|   |   |   |   |   |   |--- feature_2 <= 9000.00
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_2 >  9000.00
|   |   |   |   |   |   |   |--- feature_27 <= 27.50
|   |   |   |   |   |   |   |   |--- feature_24 <= 1690.00
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_24 >  1690.00
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_27 >  27.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_12 >  50.50
|   |   |   |   |   |--- feature_1 <= 1350.00
|   |   |   |   |   |   |--- feature_2 <= 14000.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_2 >  14000.00
|   |   |   |   |   |   |   |--- feature_12 <= 86.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_12 >  86.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_1 >  1350.00
|   |   |   |   |   |   |--- feature_0 <= 51.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_0 >  51.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |--- feature_12 >  103.50
|   |   |   |--- feature_4 <= 89.00
|   |   |   |   |--- feature_27 <= 32.50
|   |   |   |   |   |--- feature_1 <= 1075.00
|   |   |   |   |   |   |--- feature_20 <= 0.50
|   |   |   |   |   |   |   |--- feature_0 <= 29.50
|   |   |   |   |   |   |   |   |--- feature_12 <= 160.00
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_12 >  160.00
|   |   |   |   |   |   |   |   |   |--- feature_1 <= 900.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_1 >  900.00
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_0 >  29.50
|   |   |   |   |   |   |   |   |--- feature_15 <= 0.50
|   |   |   |   |   |   |   |   |   |--- feature_1 <= 960.00
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_1 >  960.00
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 34.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  34.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_15 >  0.50
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_20 >  0.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_1 >  1075.00
|   |   |   |   |   |   |--- feature_0 <= 57.50
|   |   |   |   |   |   |   |--- feature_27 <= 11.50
|   |   |   |   |   |   |   |   |--- feature_12 <= 211.50
|   |   |   |   |   |   |   |   |   |--- feature_4 <= 40.00
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_4 >  40.00
|   |   |   |   |   |   |   |   |   |   |--- feature_6 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_6 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_12 >  211.50
|   |   |   |   |   |   |   |   |   |--- feature_2 <= 14000.00
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_2 >  14000.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_27 >  11.50
|   |   |   |   |   |   |   |   |--- feature_2 <= 7250.00
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 51.50
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_0 >  51.50
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 52.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  52.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_2 >  7250.00
|   |   |   |   |   |   |   |   |   |--- feature_2 <= 8500.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_2 >  8500.00
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 56.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  56.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_0 >  57.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_27 >  32.50
|   |   |   |   |   |--- feature_0 <= 55.50
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_0 >  55.50
|   |   |   |   |   |   |--- class: 1
|   |   |   |--- feature_4 >  89.00
|   |   |   |   |--- feature_24 <= 1727.50
|   |   |   |   |   |--- feature_3 <= 500.00
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_3 >  500.00
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_24 >  1727.50
|   |   |   |   |   |--- feature_12 <= 196.50
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_12 >  196.50
|   |   |   |   |   |   |--- class: 1
|--- feature_25 >  0.50
|   |--- feature_16 <= 0.50
|   |   |--- feature_12 <= 74.50
|   |   |   |--- feature_2 <= 4250.00
|   |   |   |   |--- feature_12 <= 20.00
|   |   |   |   |   |--- feature_27 <= 1.50
|   |   |   |   |   |   |--- feature_8 <= 0.50
|   |   |   |   |   |   |   |--- feature_27 <= 0.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_27 >  0.50
|   |   |   |   |   |   |   |   |--- feature_24 <= 1457.50
|   |   |   |   |   |   |   |   |   |--- feature_4 <= 55.00
|   |   |   |   |   |   |   |   |   |   |--- feature_6 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_6 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_4 >  55.00
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_24 >  1457.50
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_8 >  0.50
|   |   |   |   |   |   |   |--- feature_4 <= 40.00
|   |   |   |   |   |   |   |   |--- feature_28 <= 42.00
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_28 >  42.00
|   |   |   |   |   |   |   |   |   |--- feature_27 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_27 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_4 >  40.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_27 >  1.50
|   |   |   |   |   |   |--- feature_2 <= 2450.00
|   |   |   |   |   |   |   |--- feature_1 <= 1335.00
|   |   |   |   |   |   |   |   |--- feature_1 <= 975.00
|   |   |   |   |   |   |   |   |   |--- feature_24 <= 956.00
|   |   |   |   |   |   |   |   |   |   |--- feature_19 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- feature_19 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_24 >  956.00
|   |   |   |   |   |   |   |   |   |   |--- feature_28 <= 9.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- feature_28 >  9.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |--- feature_1 >  975.00
|   |   |   |   |   |   |   |   |   |--- feature_6 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- feature_10 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- feature_10 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_6 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_1 >  1335.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_2 >  2450.00
|   |   |   |   |   |   |   |--- feature_3 <= 60.00
|   |   |   |   |   |   |   |   |--- feature_8 <= 0.50
|   |   |   |   |   |   |   |   |   |--- feature_24 <= 892.50
|   |   |   |   |   |   |   |   |   |   |--- feature_27 <= 5.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_27 >  5.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_24 >  892.50
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_8 >  0.50
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_3 >  60.00
|   |   |   |   |   |   |   |   |--- feature_27 <= 2.50
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_27 >  2.50
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_12 >  20.00
|   |   |   |   |   |--- feature_4 <= 71.00
|   |   |   |   |   |   |--- feature_3 <= 900.00
|   |   |   |   |   |   |   |--- feature_1 <= 795.00
|   |   |   |   |   |   |   |   |--- feature_24 <= 425.00
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_24 >  425.00
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 60.00
|   |   |   |   |   |   |   |   |   |   |--- feature_24 <= 1058.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 7
|   |   |   |   |   |   |   |   |   |   |--- feature_24 >  1058.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_0 >  60.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_1 >  795.00
|   |   |   |   |   |   |   |   |--- feature_24 <= 872.50
|   |   |   |   |   |   |   |   |   |--- class: 1

In [60]:
dt = DecisionTreeClassifier(max_depth=3)
dt.fit(X_train, y_train)
 
y_pred = dt.predict_proba(X_train)[:, 1]
auc = roc_auc_score(y_train, y_pred)
print('train', auc)
 
y_pred = dt.predict_proba(X_val)[:, 1]
auc = roc_auc_score(y_val, y_pred)
print('val', auc)

train 0.7761016984958594
val 0.7389079944782155

In [61]:
print(export_text(dt))

|--- feature_25 <= 0.50
|   |--- feature_27 <= 6.50
|   |   |--- feature_1 <= 862.50
|   |   |   |--- class: 0
|   |   |--- feature_1 >  862.50
|   |   |   |--- class: 1
|   |--- feature_27 >  6.50
|   |   |--- feature_12 <= 103.50
|   |   |   |--- class: 1
|   |   |--- feature_12 >  103.50
|   |   |   |--- class: 0
|--- feature_25 >  0.50
|   |--- feature_16 <= 0.50
|   |   |--- feature_12 <= 74.50
|   |   |   |--- class: 0
|   |   |--- feature_12 >  74.50
|   |   |   |--- class: 0
|   |--- feature_16 >  0.50
|   |   |--- feature_2 <= 8750.00
|   |   |   |--- class: 1
|   |   |--- feature_2 >  8750.00
|   |   |   |--- class: 0

In [62]:
names = dv.get_feature_names_out().tolist()
print(export_text(dt, feature_names=names))

|--- records=no <= 0.50
|   |--- seniority <= 6.50
|   |   |--- amount <= 862.50
|   |   |   |--- class: 0
|   |   |--- amount >  862.50
|   |   |   |--- class: 1
|   |--- seniority >  6.50
|   |   |--- income <= 103.50
|   |   |   |--- class: 1
|   |   |--- income >  103.50
|   |   |   |--- class: 0
|--- records=no >  0.50
|   |--- job=partime <= 0.50
|   |   |--- income <= 74.50
|   |   |   |--- class: 0
|   |   |--- income >  74.50
|   |   |   |--- class: 0
|   |--- job=partime >  0.50
|   |   |--- assets <= 8750.00
|   |   |   |--- class: 1
|   |   |--- assets >  8750.00
|   |   |   |--- class: 0